version: '3'
services:

  # carco-web:
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - postgres
  #   environment:
  #     - DATABASE_URL
  #     - PORT
  #   command: bash -c "./wait-for-it.sh postgres:5432 -- yarn migrate up && yarn prod"
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - public

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "supersecretpswd"
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data
    networks:
      - public

networks:
  public:

volumes:
  db-data:
